# An array of some major cities in Canada
CANADIAN_CITIES = [
    "Toronto",
    "Montreal",
    "Vancouver",
    "Calgary",
    "Edmonton",
    "Ottawa",
    "Winnipeg",
    "Quebec City",
    "Hamilton",
    "London",
    "Kitchener",
    "Victoria",
    "Halifax",
    "Oshawa",
    "Windsor",
    "Saskatoon",
    "Regina",
    "St. John's",
    "Barrie",
    "Sherbrooke",
    "Kelowna",
    "Abbotsford",
    "Kingston",
    "Guelph",
    "Moncton",
    "Brantford",
    "Saint John",
    "Thunder Bay",
    "Peterborough",
    "Lethbridge",
    "Nanaimo",
    "Kamloops",
    "Belleville",
    "Chatham-Kent",
    "Fredericton",
    "Charlottetown",
    "Fort McMurray",
    "Prince George",
    "Red Deer",
    "Medicine Hat",
    "North Bay",
    "Grande Prairie",
    "Chilliwack",
    "Saint-Jérôme",
    "Drummondville",
    "Timmins",
    "Orillia",
    "Airdrie",
    "Laval",
    "Burlington",
    "Sherwood Park",
    "Trois-Rivières",
    "Gatineau",
    "Lévis",
    "Surrey",
    "Langley",
    "Coquitlam",
    "Vaughan",
    "Markham",
    "Richmond Hill",
    "Brampton",
    "Mississauga",
    "Burnaby",
    "Richmond",
    "Surrey",
    "Halifax",
    "St. John's",
    "Victoria",
    "Regina",
    "Charlottetown",
    "Whitehorse",
    "Yellowknife",
    "Iqaluit",
    # Add more cities as needed...
]